### ISSUE TITLE
AttributeError: 'DistributedDataParallel' object has no attribute 'base_model'

### ISSUE THREAD

**Issue by maschenb** [thuanz123/realfill#8]
Hello.  Thank you for your code!  However, I'm getting the following error when I run it on a machine with 2 NVIDIA RTX A6000s after 500 steps.

```
Steps:  25%|████████████████████████                                                                        | 500/2000 [34:15<1:39:43,  3.99s/it, loss=0.0361]11/09/2023 21:23:13 - INFO - accelerate.accelerator - Saving current state to flowerwoman-model/checkpoint-500
Traceback (most recent call last):
  File "train_realfill.py", line 956, in <module>
    main(args)
  File "train_realfill.py", line 894, in main
    accelerator.save_state(save_path)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 2793, in save_state
    hook(self._models, weights, output_dir)
  File "train_realfill.py", line 634, in save_model_hook
    sub_dir = "unet" if isinstance(model.base_model.model, type(accelerator.unwrap_model(unet.base_model.model))) else "text_encoder"
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'base_model'
```

I'm working in a docker.  Here are the steps I take to get to that error with your default example:
```
#start a container like so:
#docker run -it --rm --ipc=host --gpus all nvidia/cuda:11.7.1-devel-ubuntu20.04

apt update
apt install git
apt install python3-pip

mkdir GitClones
cd GitClones
git clone https://github.com/thuanz123/realfill
cd realfill
pip install -r requirements.txt 

accelerate config default
#Run example https://github.com/thuanz123/realfill#toy-example
```
I would be grateful for any feedback!

**Comment by thuanz123** [comment]
It seems like the current code is only work for 1 gpu, it does not work with distributed training. I will try to fix it when I have time

**Comment by thuanz123** [comment]
distributed training should work now

**Comment by maschenb** [comment]
> distributed training should work now

Thanks a bunch!  I will test it this week.
